export enum TASK_ID {
  // aave
  AAVE_AVALANCHE_LENDING = 'AAVE_AVALANCHE_LENDING',
  AAVE_POLYGON_LENDING = 'AAVE_POLYGON_LENDING',

  // air nft
  AIR_NFT_BINANCE_SMART_CHAIN_NFT = 'AIR_NFT_BINANCE_SMART_CHAIN_NFT',

  // ape swap
  APE_SWAP_BINANCE_SMART_CHAIN_DEX = 'APE_SWAP_BINANCE_SMART_CHAIN_DEX',
  APE_SWAP_BINANCE_SMART_CHAIN_FARM = 'APE_SWAP_BINANCE_SMART_CHAIN_FARM',
  APE_SWAP_BINANCE_SMART_CHAIN_NFT = 'APE_SWAP_BINANCE_SMART_CHAIN_NFT',

  APE_SWAP_POLYGON_DEX = 'APE_SWAP_POLYGON_DEX',
  APE_SWAP_POLYGON_FARM = 'APE_SWAP_POLYGON_FARM',

  // auto farm
  AUTO_FARM_BINANCE_SMART_CHAIN_FARM = 'AUTO_FARM_BINANCE_SMART_CHAIN_FARM',

  // bakery swap
  BAKERY_SWAP_BINANCE_SMART_CHAIN_DEX = 'BAKERY_SWAP_BINANCE_SMART_CHAIN_DEX',
  BAKERY_SWAP_BINANCE_SMART_CHAIN_FARM = 'BAKERY_SWAP_BINANCE_SMART_CHAIN_FARM',

  // bi swap
  BI_SWAP_BINANCE_SMART_CHAIN_DEX = 'BI_SWAP_BINANCE_SMART_CHAIN_DEX',
  BI_SWAP_BINANCE_SMART_CHAIN_FARM = 'BI_SWAP_BINANCE_SMART_CHAIN_FARM',

  // klay swap
  KLAY_SWAP_KLAYTN_DEX = 'KLAY_SWAP_KLAYTN_DEX',

  // mdex
  MDEX_BINANCE_SMART_CHAIN_DEX = 'MDEX_BINANCE_SMART_CHAIN_DEX',
  MDEX_BINANCE_SMART_CHAIN_FARM = 'MDEX_BINANCE_SMART_CHAIN_FARM',

  MDEX_HECO_DEX = 'MDEX_HECO_DEX',
  MDEX_HECO_FARM = 'MDEX_HECO_FARM',

  // pancake swap
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_DEX = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_DEX',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_FARM = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_FARM',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_FARM_2 = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_FARM_2',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_2 = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_2',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_3 = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_3',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_4 = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_4',
  PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_5 = 'PANCAKE_SWAP_BINANCE_SMART_CHAIN_NFT_5',

  // quick swap
  QUICK_SWAP_POLYGON_DEX = 'QUICK_SWAP_POLYGON_DEX',
  QUICK_SWAP_POLYGON_FARM = 'QUICK_SWAP_POLYGON_FARM',
  QUICK_SWAP_POLYGON_FARM_2 = 'QUICK_SWAP_POLYGON_FARM_2',
}
