export enum TASK_ID {
  // aave
  AAVE_AVALANCHE_LENDING = 'AAVE_AVALANCHE_LENDING',
  AAVE_POLYGON_LENDING = 'AAVE_POLYGON_LENDING',

  // air nft
  AIR_NFT_BINANCE_SMART_CHAIN_NFT = 'AIR_NFT_BINANCE_SMART_CHAIN_NFT',

  // ape swap
  APE_SWAP_BINANCE_SMART_CHAIN_DEX = 'APE_SWAP_BINANCE_SMART_CHAIN_DEX',
  APE_SWAP_BINANCE_SMART_CHAIN_FARM = 'APE_SWAP_BINANCE_SMART_CHAIN_FARM',
  APE_SWAP_BINANCE_SMART_CHAIN_NFT = 'APE_SWAP_BINANCE_SMART_CHAIN_NFT',

  APE_SWAP_POLYGON_DEX = 'APE_SWAP_POLYGON_DEX',
  APE_SWAP_POLYGON_FARM = 'APE_SWAP_POLYGON_FARM',

  // auto farm
  AUTO_FARM_BINANCE_SMART_CHAIN_FARM = 'AUTO_FARM_BINANCE_SMART_CHAIN_FARM',

  // bakery swap
  BAKERY_SWAP_BINANCE_SMART_CHAIN_DEX = 'BAKERY_SWAP_BINANCE_SMART_CHAIN_DEX',
  BAKERY_SWAP_BINANCE_SMART_CHAIN_FARM = 'BAKERY_SWAP_BINANCE_SMART_CHAIN_FARM',
}
